


# TODOs:
# pull a python image
# create katyusha group and user with password
# move the whole project into the katyusha home directory
# install all necessary dependencies like pm2 and from requirements.txt
# change the owner of the folder containing the source code
# run the katyusha.py server in development mode using "pm2 start katyusha.py" command
