


# TODOs:
# pull a rust image
# create katyusha group and user with password
# move the whole project into the katyusha home directory
# change the owner of the folder containing the source code
# run the bot in development mode using "cargo run" command
